import type {
  Lead,
  ContentItem,
  Approval,
  Conversation,
  AutomationTask,
  SocialConnection,
  DashboardStats,
  AnalyticsData,
  WebsiteData,
  SettingsData,
  BillingData,
} from "@/types";

export const dashboardStats: DashboardStats = {
  totalLeads: 2483,
  leadsGrowth: 12.5,
  contentPublished: 847,
  contentGrowth: 8.3,
  conversationsActive: 126,
  conversationsGrowth: -3.2,
  meetingsBooked: 64,
  meetingsGrowth: 18.7,
  revenue: 284500,
  revenueGrowth: 22.4,
  responseRate: 94.2,
  responseGrowth: 2.1,
};

export const leads: Lead[] = [
  {
    id: "ld-001",
    name: "Sarah Mitchell",
    company: "NexHealth Technologies",
    email: "sarah.mitchell@nexhealth.com",
    phone: "+1 (415) 867-5309",
    industry: "Healthcare",
    leadScore: 92,
    status: "qualified",
    location: "San Francisco, CA",
    createdAt: "2025-01-15",
    lastContact: "2025-01-20",
    notes: "Interested in automation for patient outreach. Budget approved for Q1.",
  },
  {
    id: "ld-002",
    name: "James Kowalski",
    company: "Apex Capital Partners",
    email: "j.kowalski@apexcapital.com",
    phone: "+1 (212) 555-0142",
    industry: "FinTech",
    leadScore: 88,
    status: "contacted",
    location: "New York, NY",
    createdAt: "2025-01-14",
    lastContact: "2025-01-19",
  },
  {
    id: "ld-003",
    name: "Priya Ramachandran",
    company: "CloudScale SaaS Inc.",
    email: "priya@cloudscale.io",
    phone: "+1 (408) 555-7321",
    industry: "SaaS",
    leadScore: 95,
    status: "qualified",
    location: "San Jose, CA",
    createdAt: "2025-01-13",
    lastContact: "2025-01-21",
    notes: "Current MRR $2.4M, looking to scale outreach. Referred by Marcus.",
  },
  {
    id: "ld-004",
    name: "David Okafor",
    company: "Meridian Logistics Group",
    email: "d.okafor@meridianlog.com",
    phone: "+1 (312) 555-8901",
    industry: "Logistics",
    leadScore: 71,
    status: "new",
    location: "Chicago, IL",
    createdAt: "2025-01-20",
    lastContact: "2025-01-20",
  },
  {
    id: "ld-005",
    name: "Emily Chen",
    company: "Brightlane Education",
    email: "emily.chen@brightlane.edu",
    phone: "+1 (617) 555-3456",
    industry: "Education",
    leadScore: 84,
    status: "nurturing",
    location: "Boston, MA",
    createdAt: "2025-01-10",
    lastContact: "2025-01-18",
  },
  {
    id: "ld-006",
    name: "Robert Gutierrez",
    company: "Sterling Realty Group",
    email: "robert@sterlingrealty.com",
    phone: "+1 (305) 555-6677",
    industry: "Real Estate",
    leadScore: 67,
    status: "contacted",
    location: "Miami, FL",
    createdAt: "2025-01-18",
    lastContact: "2025-01-19",
  },
  {
    id: "ld-007",
    name: "Amanda Foster",
    company: "Harbor Legal Advisors",
    email: "a.foster@harborlegal.com",
    phone: "+1 (202) 555-9901",
    industry: "Legal",
    leadScore: 78,
    status: "new",
    location: "Washington, DC",
    createdAt: "2025-01-21",
    lastContact: "2025-01-21",
  },
  {
    id: "ld-008",
    name: "Kevin Nakamura",
    company: "Forge Manufacturing Co.",
    email: "k.nakamura@forgemfg.com",
    phone: "+1 (512) 555-4488",
    industry: "Manufacturing",
    leadScore: 55,
    status: "lost",
    location: "Austin, TX",
    createdAt: "2024-12-05",
    lastContact: "2025-01-10",
  },
  {
    id: "ld-009",
    name: "Lauren Whitfield",
    company: "BrandPulse Digital",
    email: "lauren@brandpulse.co",
    phone: "+1 (310) 555-1200",
    industry: "Marketing",
    leadScore: 90,
    status: "qualified",
    location: "Los Angeles, CA",
    createdAt: "2025-01-08",
    lastContact: "2025-01-20",
    notes: "Agency with 40+ clients. Interested in white-label solution.",
  },
  {
    id: "ld-010",
    name: "Marcus Webb",
    company: "Sentinel Commerce Inc.",
    email: "marcus.webb@sentinelcommerce.com",
    phone: "+1 (720) 555-3002",
    industry: "E-commerce",
    leadScore: 86,
    status: "converted",
    location: "Denver, CO",
    createdAt: "2024-12-20",
    lastContact: "2025-01-15",
    notes: "Converted after 14-day trial. Annual contract worth $48K.",
  },
  {
    id: "ld-011",
    name: "Tanya Petrova",
    company: "Vantage Analytics",
    email: "tanya@vantageanalytics.com",
    phone: "+1 (206) 555-5111",
    industry: "SaaS",
    leadScore: 73,
    status: "new",
    location: "Seattle, WA",
    createdAt: "2025-01-22",
    lastContact: "2025-01-22",
  },
  {
    id: "ld-012",
    name: "Carlos Mendez",
    company: "VidaCare Solutions",
    email: "carlos.mendez@vidacare.com",
    phone: "+1 (602) 555-8822",
    industry: "Healthcare",
    leadScore: 81,
    status: "nurturing",
    location: "Phoenix, AZ",
    createdAt: "2025-01-05",
    lastContact: "2025-01-17",
  },
];

export const contentItems: ContentItem[] = [
  {
    id: "ct-001",
    title: "Why AI-Powered Lead Generation Is Eating Traditional Sales Outreach",
    type: "carousel",
    platform: "linkedin",
    status: "published",
    date: "2025-01-20",
    author: "Ava Martinez",
    engagement: { likes: 847, comments: 132, shares: 56 },
  },
  {
    id: "ct-002",
    title: "Behind the Scenes: How DataBuks Automates 10K+ Conversations Daily",
    type: "reel",
    platform: "instagram",
    status: "published",
    date: "2025-01-19",
    author: "Jordan Lee",
    engagement: { likes: 2300, comments: 412, shares: 189 },
  },
  {
    id: "ct-003",
    title: "Customer Success Story: From 0 to $2M Pipeline in 90 Days",
    type: "post",
    platform: "facebook",
    status: "scheduled",
    date: "2025-01-25",
    author: "Ava Martinez",
  },
  {
    id: "ct-004",
    title: "Q1 2025 Social Media Strategy Teaser",
    type: "story",
    platform: "instagram",
    status: "draft",
    date: "2025-01-22",
    author: "Jordan Lee",
  },
  {
    id: "ct-005",
    title: "The Ultimate Guide to Automated DM Campaigns That Convert",
    type: "email",
    platform: "email",
    status: "draft",
    date: "2025-01-21",
    author: "Rachel Kim",
  },
  {
    id: "ct-006",
    title: "3 Automation Workflows Every Marketing Team Needs in 2025",
    type: "carousel",
    platform: "linkedin",
    status: "published",
    date: "2025-01-18",
    author: "Ava Martinez",
    engagement: { likes: 621, comments: 88, shares: 42 },
  },
  {
    id: "ct-007",
    title: "How We Reduced Response Time by 94% With Our AI Engine",
    type: "post",
    platform: "twitter",
    status: "scheduled",
    date: "2025-01-24",
    author: "Rachel Kim",
  },
  {
    id: "ct-008",
    title: "New Feature Drop: Multi-Platform Content Scheduling Is Live",
    type: "reel",
    platform: "instagram",
    status: "draft",
    date: "2025-01-23",
    author: "Jordan Lee",
  },
  {
    id: "ct-009",
    title: "WhatsApp Business API Integration Now Available for All Plans",
    type: "post",
    platform: "whatsapp",
    status: "published",
    date: "2025-01-17",
    author: "Ava Martinez",
    engagement: { likes: 340, comments: 97, shares: 23 },
  },
  {
    id: "ct-010",
    title: "Monthly Roundup: Top Performing Content and What We Learned",
    type: "email",
    platform: "email",
    status: "scheduled",
    date: "2025-01-28",
    author: "Rachel Kim",
  },
];

export const approvals: Approval[] = [
  {
    id: "ap-001",
    type: "post",
    content: "We're excited to announce our new partnership with Stripe for seamless payment processing across all plans. Launching February 1st.",
    platform: "linkedin",
    submittedBy: "Ava Martinez",
    date: "2025-01-22",
    status: "pending",
    urgency: "high",
  },
  {
    id: "ap-002",
    type: "dm",
    content: "Hi [Name], thanks for reaching out! We'd love to hop on a quick call to walk you through our new enterprise features. Are you free Thursday 3PM EST?",
    platform: "instagram",
    submittedBy: "Jordan Lee",
    date: "2025-01-21",
    status: "pending",
    urgency: "medium",
  },
  {
    id: "ap-003",
    type: "reply",
    content: "Great question! Our AI engine processes over 50K interactions per minute with a 99.7% accuracy rate on intent detection. Happy to share the case study.",
    platform: "twitter",
    submittedBy: "Rachel Kim",
    date: "2025-01-22",
    status: "pending",
    urgency: "low",
  },
  {
    id: "ap-004",
    type: "comment",
    content: "Absolutely agree with this take. We've seen B2B companies double their pipeline within 60 days of implementing automated outreach. The key is personalization at scale.",
    platform: "linkedin",
    submittedBy: "Ava Martinez",
    date: "2025-01-20",
    status: "approved",
    urgency: "low",
  },
  {
    id: "ap-005",
    type: "post",
    content: "BREAKING: DataBuks just crossed 10,000 active business users worldwide. Thank you to our incredible community for making this possible.",
    platform: "facebook",
    submittedBy: "Jordan Lee",
    date: "2025-01-19",
    status: "pending",
    urgency: "high",
  },
  {
    id: "ap-006",
    type: "dm",
    content: "Hey! Noticed you've been checking out our analytics dashboard. Want a personalized walkthrough? I can show you how to track lead conversion rates in real-time.",
    platform: "whatsapp",
    submittedBy: "Rachel Kim",
    date: "2025-01-21",
    status: "pending",
    urgency: "medium",
  },
  {
    id: "ap-007",
    type: "reply",
    content: "Hi Sarah, the integration takes less than 10 minutes. Our support team can white-glove the setup if needed. Just let us know a time that works.",
    platform: "instagram",
    submittedBy: "Jordan Lee",
    date: "2025-01-22",
    status: "pending",
    urgency: "medium",
  },
  {
    id: "ap-008",
    type: "comment",
    content: "This is gold. We implemented a similar approach and saw a 40% reduction in churn within the first quarter.",
    platform: "linkedin",
    submittedBy: "Ava Martinez",
    date: "2025-01-18",
    status: "rejected",
    urgency: "low",
  },
];

export const conversations: Conversation[] = [
  {
    id: "cn-001",
    name: "Alex Thompson",
    lastMessage: "Sounds great! Let me check with my team and I'll get back to you by Friday.",
    time: "2m ago",
    unread: 3,
    platform: "instagram",
    status: "online",
  },
  {
    id: "cn-002",
    name: "Maria Santos",
    lastMessage: "Can you send over the pricing PDF for the enterprise plan?",
    time: "8m ago",
    unread: 1,
    platform: "whatsapp",
    status: "online",
  },
  {
    id: "cn-003",
    name: "Derek Johnson",
    lastMessage: "Thanks for the demo. We're ready to move forward with the annual plan.",
    time: "15m ago",
    unread: 0,
    platform: "facebook",
    status: "away",
  },
  {
    id: "cn-004",
    name: "Sophie Laurent",
    lastMessage: "The integration with HubSpot was seamless. Our team loves it so far.",
    time: "32m ago",
    unread: 0,
    platform: "linkedin",
    status: "offline",
    tags: ["enterprise", "hubspot"],
  },
  {
    id: "cn-005",
    name: "Ryan Patel",
    lastMessage: "Is there a way to set up automated follow-up sequences based on lead score?",
    time: "1h ago",
    unread: 2,
    platform: "telegram",
    status: "offline",
  },
  {
    id: "cn-006",
    name: "Jennifer Walsh",
    lastMessage: "We're seeing an issue with the analytics dashboard not updating in real-time.",
    time: "2h ago",
    unread: 1,
    platform: "instagram",
    status: "offline",
    tags: ["support", "bug"],
  },
  {
    id: "cn-007",
    name: "Omar Hassan",
    lastMessage: "Perfect, I'll share the onboarding deck with the rest of the team tomorrow.",
    time: "3h ago",
    unread: 0,
    platform: "whatsapp",
    status: "offline",
  },
  {
    id: "cn-008",
    name: "Chloe Williams",
    lastMessage: "Do you offer SOC 2 compliance for the enterprise tier? This is critical for us.",
    time: "5h ago",
    unread: 0,
    platform: "linkedin",
    status: "offline",
    tags: ["enterprise", "security"],
  },
  {
    id: "cn-009",
    name: "Nathan Brooks",
    lastMessage: "Hey, quick question about the API rate limits. Our usage is about to hit the cap.",
    time: "6h ago",
    unread: 1,
    platform: "telegram",
    status: "offline",
    tags: ["api", "support"],
  },
  {
    id: "cn-010",
    name: "Isabella Rossi",
    lastMessage: "Your content automation literally saved us 20 hours per week. Just wanted to say thanks!",
    time: "8h ago",
    unread: 0,
    platform: "instagram",
    status: "offline",
  },
];

export const analyticsData: AnalyticsData = {
  reach: 184230,
  impressions: 492100,
  followers: 48750,
  replies: 3840,
  qualifiedLeads: 312,
  meetings: 64,
  revenue: 284500,
  growth: 22.4,
  reachChart: [
    { date: "Jan 1", value: 12400 },
    { date: "Jan 3", value: 18100 },
    { date: "Jan 5", value: 15300 },
    { date: "Jan 7", value: 21200 },
    { date: "Jan 9", value: 19500 },
    { date: "Jan 11", value: 24700 },
    { date: "Jan 13", value: 22100 },
    { date: "Jan 15", value: 26800 },
    { date: "Jan 17", value: 29300 },
    { date: "Jan 19", value: 31200 },
    { date: "Jan 21", value: 35800 },
  ],
  impressionsChart: [
    { date: "Jan 1", value: 34100 },
    { date: "Jan 3", value: 42800 },
    { date: "Jan 5", value: 39500 },
    { date: "Jan 7", value: 51200 },
    { date: "Jan 9", value: 48700 },
    { date: "Jan 11", value: 56300 },
    { date: "Jan 13", value: 52900 },
    { date: "Jan 15", value: 61400 },
    { date: "Jan 17", value: 67200 },
    { date: "Jan 19", value: 71800 },
    { date: "Jan 21", value: 82100 },
  ],
  followersChart: [
    { date: "Jan 1", value: 42100 },
    { date: "Jan 3", value: 42450 },
    { date: "Jan 5", value: 42900 },
    { date: "Jan 7", value: 43300 },
    { date: "Jan 9", value: 43800 },
    { date: "Jan 11", value: 44200 },
    { date: "Jan 13", value: 44800 },
    { date: "Jan 15", value: 45300 },
    { date: "Jan 17", value: 46000 },
    { date: "Jan 19", value: 47200 },
    { date: "Jan 21", value: 48750 },
  ],
  engagementChart: [
    { date: "Jan 1", value: 8.2 },
    { date: "Jan 3", value: 7.8 },
    { date: "Jan 5", value: 9.1 },
    { date: "Jan 7", value: 8.5 },
    { date: "Jan 9", value: 9.7 },
    { date: "Jan 11", value: 10.2 },
    { date: "Jan 13", value: 9.4 },
    { date: "Jan 15", value: 11.1 },
    { date: "Jan 17", value: 10.8 },
    { date: "Jan 19", value: 12.3 },
    { date: "Jan 21", value: 13.5 },
  ],
};

export const automationTasks: AutomationTask[] = [
  {
    id: "at-001",
    name: "Instagram DM Outreach - SaaS Founders",
    agent: "LeadGen Agent v2",
    status: "running",
    progress: 64,
    time: "Running for 2h 14m",
    description: "Sending personalized DMs to 150 SaaS founders in the US.",
  },
  {
    id: "at-002",
    name: "LinkedIn Content Scheduler - Weekly Posts",
    agent: "Content Agent",
    status: "completed",
    progress: 100,
    time: "Completed 1h ago",
    description: "Published 5 LinkedIn posts across company page.",
    lastRun: "2025-01-22 09:00 AM",
  },
  {
    id: "at-003",
    name: "Lead Scoring Batch Processing",
    agent: "Scoring Engine v3",
    status: "running",
    progress: 82,
    time: "Running for 45m",
    description: "Re-scoring 2,483 leads based on updated engagement data.",
  },
  {
    id: "at-004",
    name: "WhatsApp Follow-up Sequence",
    agent: "Sequence Agent",
    status: "queued",
    progress: 0,
    time: "Scheduled for 2:00 PM",
    description: "Automated follow-up for 85 leads who haven't responded in 48h.",
  },
  {
    id: "at-005",
    name: "Email Newsletter - January Edition",
    agent: "Content Agent",
    status: "completed",
    progress: 100,
    time: "Completed 3h ago",
    description: "Sent monthly newsletter to 12,400 subscribers.",
    lastRun: "2025-01-22 07:30 AM",
  },
  {
    id: "at-006",
    name: "Facebook Ad Comment Responder",
    agent: "Reply Agent",
    status: "running",
    progress: 45,
    time: "Running for 1h 8m",
    description: "Auto-responding to comments on active Facebook ad campaigns.",
  },
  {
    id: "at-007",
    name: "Telegram Community Moderation",
    agent: "Moderation Agent",
    status: "failed",
    progress: 23,
    time: "Failed 30m ago",
    description: "API rate limit exceeded. Retrying in 15 minutes.",
  },
  {
    id: "at-008",
    name: "Competitor Analysis Report Generation",
    agent: "Analytics Agent",
    status: "queued",
    progress: 0,
    time: "Scheduled for 6:00 PM",
    description: "Generating weekly competitor analysis for 12 tracked competitors.",
  },
  {
    id: "at-009",
    name: "Instagram Story Auto-Posting",
    agent: "Content Agent",
    status: "completed",
    progress: 100,
    time: "Completed 30m ago",
    description: "Posted 3 Instagram stories at optimal engagement times.",
    lastRun: "2025-01-22 10:30 AM",
  },
  {
    id: "at-010",
    name: "CRM Sync - Salesforce Integration",
    agent: "Sync Agent",
    status: "running",
    progress: 91,
    time: "Running for 12m",
    description: "Syncing updated lead data between DataBuks and Salesforce.",
  },
  {
    id: "at-011",
    name: "LinkedIn Connection Requests",
    agent: "LeadGen Agent v2",
    status: "queued",
    progress: 0,
    time: "Scheduled for 4:00 PM",
    description: "Sending 200 connection requests to target ICP profiles.",
  },
  {
    id: "at-012",
    name: "Sentiment Analysis Pipeline",
    agent: "Analytics Agent",
    status: "running",
    progress: 37,
    time: "Running for 22m",
    description: "Analyzing sentiment on 850 recent conversations for quality scoring.",
  },
];

export const websiteData: WebsiteData = {
  businessName: "DataBuks",
  tagline: "AI-Powered Outreach That Converts",
  summary: "DataBuks is an all-in-one AI-powered outreach platform that helps B2B companies automate lead generation, content publishing, and customer conversations across Instagram, Facebook, WhatsApp, LinkedIn, and Telegram. Our proprietary AI engine processes millions of interactions daily to identify high-intent leads, personalize outreach at scale, and drive measurable revenue growth.",
  brandVoice: [
    "Professional yet approachable",
    "Data-driven and transparent",
    "Innovative and forward-thinking",
    "Customer-first, results-oriented",
    "Confident without being arrogant",
  ],
  targetAudience: [
    {
      segment: "B2B SaaS Founders & Growth Teams",
      description: "Founders, heads of growth, and marketing leads at B2B SaaS companies with 10-200 employees looking to scale their outbound pipeline without growing headcount.",
      painPoints: [
        "Manual outreach doesn't scale past 100 leads per week",
        "Response rates below 5% on cold email campaigns",
        "No visibility into which channels drive the most qualified leads",
        "Marketing and sales teams working in silos with disconnected tools",
      ],
    },
    {
      segment: "Digital Marketing Agencies",
      description: "Agency owners and account managers managing social media and lead generation for 5-50+ clients who need a white-label or multi-tenant solution.",
      painPoints: [
        "Juggling 10+ different tools to manage client accounts",
        "Inconsistent reporting across platforms",
        "Hard to prove ROI to clients without unified analytics",
        "Team burnout from repetitive manual engagement tasks",
      ],
    },
    {
      segment: "Real Estate & Financial Services",
      description: "Real estate agents, mortgage brokers, and financial advisors who rely on relationship-based selling and need to nurture leads over long sales cycles.",
      painPoints: [
        "Long sales cycles (3-12 months) make follow-up consistency difficult",
        "Leads go cold after initial contact without automated nurturing",
        "Compliance restrictions limit what and how you can communicate",
        "Hard to stand out in a crowded, trust-dependent market",
      ],
    },
  ],
  knowledgeBase: [
    {
      title: "Getting Started with DataBuks",
      content: "DataBuks onboarding takes less than 15 minutes. Connect your social accounts, import your existing leads or let our AI find them, configure your outreach preferences, and launch your first campaign. Our guided setup wizard walks you through each step.",
      category: "Onboarding",
    },
    {
      title: "How Lead Scoring Works",
      content: "Our AI Lead Scoring Engine evaluates each lead across 40+ data points including engagement history, firmographic fit, behavioral signals, and conversation intent. Leads receive a score from 0-100 updated in real-time as new interactions occur.",
      category: "Features",
    },
    {
      title: "Content Automation Best Practices",
      content: "For best results, maintain a 70/30 split between educational and promotional content. Schedule posts during peak engagement windows (typically 9-11 AM and 2-4 PM in your audience's timezone). Use carousel posts on LinkedIn for highest engagement rates.",
      category: "Content",
    },
    {
      title: "API Integration Guide",
      content: "DataBuks provides REST APIs with full CRUD access to leads, campaigns, content, and analytics. Authentication uses API keys with granular permission scopes. Rate limits are 1000 requests/minute on Pro plans and 5000/minute on Enterprise.",
      category: "Technical",
    },
    {
      title: "Compliance & Data Privacy",
      content: "DataBuks is SOC 2 Type II certified and GDPR compliant. All data is encrypted at rest (AES-256) and in transit (TLS 1.3). We maintain data processing agreements with all sub-processors and provide a Data Protection Officer contact for enterprise clients.",
      category: "Security",
    },
  ],
  competitors: [
    {
      name: "HubSpot Marketing Hub",
      url: "https://www.hubspot.com",
      strengths: ["All-in-one CRM + marketing suite", "Massive user community and resources", "Established brand trust"],
      weaknesses: ["Expensive at scale ($800+/mo for marketing hub)", "Steep learning curve", "Limited social DM automation"],
    },
    {
      name: "ManyChat",
      url: "https://manychat.com",
      strengths: ["Excellent chat automation on Instagram/Facebook", "Affordable entry pricing", "Simple flow builder UI"],
      weaknesses: ["Limited to chat-only (no LinkedIn, no content scheduling)", "No lead scoring or CRM features", "Weak analytics"],
    },
    {
      name: "Apollo.io",
      url: "https://www.apollo.io",
      strengths: ["Massive B2B contact database", "Strong email sequencing", "Good Salesforce integration"],
      weaknesses: ["Email-heavy, weak on social channels", "Data accuracy issues on contacts", "No content publishing features"],
    },
  ],
  products: [
    {
      name: "DataBuks Starter",
      description: "Perfect for solopreneurs and small teams getting started with AI-powered outreach.",
      price: "$49/month",
      features: ["500 automated DMs/month", "3 social platform connections", "Basic lead scoring", "Content scheduler (10 posts/month)", "Email support"],
    },
    {
      name: "DataBuks Pro",
      description: "For growing businesses that need multi-channel automation and advanced analytics.",
      price: "$149/month",
      features: ["5,000 automated DMs/month", "All platform connections", "Advanced AI lead scoring", "Unlimited content scheduling", "Analytics dashboard", "Priority support", "API access"],
    },
    {
      name: "DataBuks Enterprise",
      description: "Custom solution for agencies and large teams with dedicated support and white-label options.",
      price: "Custom pricing",
      features: ["Unlimited DMs and automations", "White-label dashboard", "Dedicated account manager", "Custom AI model training", "SLA guarantee", "SSO and advanced security", "Multi-team workspaces"],
    },
  ],
  services: [
    {
      name: "Managed Outreach",
      description: "Our team sets up and manages your entire outreach strategy end-to-end.",
      price: "Starting at $2,000/month",
      features: ["Strategy development", "Content creation", "Campaign management", "Weekly performance reports", "A/B testing and optimization"],
    },
    {
      name: "AI Training & Consulting",
      description: "Custom AI model training tailored to your industry, audience, and brand voice.",
      price: "$5,000 one-time",
      features: ["Custom intent detection models", "Industry-specific lead scoring", "Brand voice calibration", "30-day refinement period", "Training documentation"],
    },
    {
      name: "Integration Setup",
      description: "White-glove setup connecting DataBuks with your existing tech stack.",
      price: "$1,500 one-time",
      features: ["CRM integration (Salesforce, HubSpot, Pipedrive)", "Data migration", "Custom webhook configuration", "API workflow setup", "2 hours of team training"],
    },
  ],
};

export const socialConnections: SocialConnection[] = [
  {
    id: "sc-001",
    platform: "instagram",
    handle: "@databuks_official",
    status: "connected",
    followers: 24300,
    lastSync: "2025-01-22 10:45 AM",
  },
  {
    id: "sc-002",
    platform: "facebook",
    handle: "DataBuks",
    status: "connected",
    followers: 18700,
    lastSync: "2025-01-22 10:44 AM",
  },
  {
    id: "sc-003",
    platform: "whatsapp",
    handle: "+1 (888) 555-0147",
    status: "connected",
    followers: 0,
    lastSync: "2025-01-22 10:46 AM",
  },
  {
    id: "sc-004",
    platform: "telegram",
    handle: "@databuks_bot",
    status: "expired",
    followers: 4200,
    lastSync: "2025-01-19 03:22 PM",
  },
  {
    id: "sc-005",
    platform: "linkedin",
    handle: "company/databuks",
    status: "connected",
    followers: 11200,
    lastSync: "2025-01-22 10:45 AM",
  },
];

export const settingsData: SettingsData = {
  businessProfile: {
    name: "DataBuks Inc.",
    email: "hello@databuks.com",
    phone: "+1 (888) 555-0147",
    website: "https://www.databuks.com",
    address: "2261 Market Street #4660, San Francisco, CA 94114",
  },
  notifications: {
    emailAlerts: true,
    pushNotifications: true,
    leadNotifications: true,
    contentNotifications: false,
    weeklyReport: true,
  },
  integrations: [
    { name: "HubSpot CRM", connected: true, lastSync: "2025-01-22 09:00 AM" },
    { name: "Salesforce", connected: true, lastSync: "2025-01-22 10:12 AM" },
    { name: "Zapier", connected: true, lastSync: "2025-01-22 08:45 AM" },
    { name: "Slack", connected: false },
    { name: "Google Analytics", connected: true, lastSync: "2025-01-22 06:00 AM" },
    { name: "Stripe", connected: false },
    { name: "Calendly", connected: true, lastSync: "2025-01-22 07:30 AM" },
    { name: "Mailchimp", connected: false },
  ],
  apiKeys: [
    {
      id: "ak-001",
      name: "Production API Key",
      key: "db_prod_a1b2c3d4e5f6g7h8i9j0",
      createdAt: "2024-11-15",
      lastUsed: "2025-01-22 10:48 AM",
      permissions: ["read", "write", "delete"],
      environment: "production",
    },
    {
      id: "ak-002",
      name: "Development API Key",
      key: "db_dev_z9y8x7w6v5u4t3s2r1q0",
      createdAt: "2024-12-01",
      lastUsed: "2025-01-21 04:22 PM",
      permissions: ["read", "write"],
      environment: "development",
    },
    {
      id: "ak-003",
      name: "Sandbox Testing Key",
      key: "db_sand_k1l2m3n4o5p6q7r8s9t0",
      createdAt: "2025-01-05",
      lastUsed: "2025-01-20 11:05 AM",
      permissions: ["read"],
      environment: "sandbox",
    },
  ],
  security: {
    twoFactorEnabled: true,
    lastPasswordChange: "2024-12-28",
    loginHistory: [
      { date: "2025-01-22 08:30 AM", ip: "73.42.15.201", location: "San Francisco, CA, United States", device: "Chrome on macOS" },
      { date: "2025-01-21 09:15 PM", ip: "73.42.15.201", location: "San Francisco, CA, United States", device: "Safari on iPhone" },
      { date: "2025-01-21 02:00 PM", ip: "198.51.100.44", location: "New York, NY, United States", device: "Chrome on Windows" },
      { date: "2025-01-20 10:00 AM", ip: "203.0.113.89", location: "London, England, United Kingdom", device: "Firefox on macOS" },
    ],
  },
};

export const billingData: BillingData = {
  plan: {
    name: "DataBuks Pro",
    price: 149,
    billingCycle: "monthly",
    features: [
      "5,000 automated DMs/month",
      "All platform connections",
      "Advanced AI lead scoring",
      "Unlimited content scheduling",
      "Analytics dashboard",
      "Priority support",
      "API access",
    ],
    usage: {
      leads: { used: 2483, limit: 10000 },
      content: { used: 847, limit: 5000 },
      automations: { used: 12, limit: 25 },
      storage: { used: 8.4, limit: 50, unit: "GB" },
    },
  },
  invoices: [
    {
      id: "inv-012",
      date: "2025-01-01",
      amount: 149,
      status: "paid",
      description: "DataBuks Pro - January 2025",
    },
    {
      id: "inv-011",
      date: "2024-12-01",
      amount: 149,
      status: "paid",
      description: "DataBuks Pro - December 2024",
    },
    {
      id: "inv-010",
      date: "2024-11-01",
      amount: 149,
      status: "paid",
      description: "DataBuks Pro - November 2024",
    },
    {
      id: "inv-009",
      date: "2024-10-01",
      amount: 149,
      status: "paid",
      description: "DataBuks Pro - October 2024",
    },
  ],
  paymentMethods: [
    {
      id: "pm-001",
      type: "visa",
      lastFour: "4242",
      expiry: "12/2026",
      isDefault: true,
    },
    {
      id: "pm-002",
      type: "mastercard",
      lastFour: "8881",
      expiry: "08/2025",
      isDefault: false,
    },
  ],
};

export const chartData = {
  weekly: {
    conversations: [
      { day: "Mon", value: 184 },
      { day: "Tue", value: 212 },
      { day: "Wed", value: 256 },
      { day: "Thu", value: 238 },
      { day: "Fri", value: 301 },
      { day: "Sat", value: 142 },
      { day: "Sun", value: 98 },
    ],
    leads: [
      { day: "Mon", value: 47 },
      { day: "Tue", value: 52 },
      { day: "Wed", value: 61 },
      { day: "Thu", value: 55 },
      { day: "Fri", value: 73 },
      { day: "Sat", value: 28 },
      { day: "Sun", value: 19 },
    ],
    revenue: [
      { day: "Mon", value: 12400 },
      { day: "Tue", value: 14100 },
      { day: "Wed", value: 16800 },
      { day: "Thu", value: 15300 },
      { day: "Fri", value: 19200 },
      { day: "Sat", value: 8700 },
      { day: "Sun", value: 5400 },
    ],
  },
  monthly: {
    conversations: [
      { month: "Jan", value: 5420 },
      { month: "Feb", value: 6100 },
      { month: "Mar", value: 7850 },
      { month: "Apr", value: 8300 },
      { month: "May", value: 9100 },
      { month: "Jun", value: 8740 },
      { month: "Jul", value: 10200 },
      { month: "Aug", value: 11800 },
      { month: "Sep", value: 13100 },
      { month: "Oct", value: 12600 },
      { month: "Nov", value: 14800 },
      { month: "Dec", value: 16100 },
    ],
    leads: [
      { month: "Jan", value: 320 },
      { month: "Feb", value: 380 },
      { month: "Mar", value: 450 },
      { month: "Apr", value: 520 },
      { month: "May", value: 610 },
      { month: "Jun", value: 580 },
      { month: "Jul", value: 720 },
      { month: "Aug", value: 810 },
      { month: "Sep", value: 940 },
      { month: "Oct", value: 890 },
      { month: "Nov", value: 1050 },
      { month: "Dec", value: 1120 },
    ],
    revenue: [
      { month: "Jan", value: 48000 },
      { month: "Feb", value: 52000 },
      { month: "Mar", value: 61000 },
      { month: "Apr", value: 74000 },
      { month: "May", value: 82000 },
      { month: "Jun", value: 79000 },
      { month: "Jul", value: 94000 },
      { month: "Aug", value: 108000 },
      { month: "Sep", value: 124000 },
      { month: "Oct", value: 118000 },
      { month: "Nov", value: 142000 },
      { month: "Dec", value: 168000 },
    ],
    growth: [
      { month: "Jan", value: 8.2 },
      { month: "Feb", value: 9.5 },
      { month: "Mar", value: 12.1 },
      { month: "Apr", value: 10.8 },
      { month: "May", value: 14.3 },
      { month: "Jun", value: 11.7 },
      { month: "Jul", value: 15.9 },
      { month: "Aug", value: 18.2 },
      { month: "Sep", value: 21.4 },
      { month: "Oct", value: 17.8 },
      { month: "Nov", value: 22.6 },
      { month: "Dec", value: 24.1 },
    ],
  },
};
